In [3]:
# Many to One LSTM

from keras.models import Model
from keras.layers import Input, Dense, LSTM
import numpy as np

x = np.array([[[1.], [2.], [3.], [4.], [5.]]])
y = np.array([[6.]])
print(x.shape, y.shape)

(1, 5, 1) (1, 1)


In [19]:
xInput = Input(batch_shape=(None, 5, 1))
xLstm = LSTM(3)(xInput)
xOutput = Dense(1)(xLstm)

model = Model(xInput, xOutput)
model.compile(loss='mean_squared_error', optimizer='adam')
print(model.summary())

Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         [(None, 5, 1)]            0         
_________________________________________________________________
lstm_3 (LSTM)                (None, 3)                 60        
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 4         
Total params: 64
Trainable params: 64
Non-trainable params: 0
_________________________________________________________________
None


In [100]:
model.fit(x, y, epochs=50, batch_size=1, verbose=0)
model.predict(x, batch_size=1)

array([[5.9999824]], dtype=float32)

In [101]:
# Many to Many LSTM

from keras.layers import TimeDistributed

x = np.array([[[1.], [2.], [3.], [4.], [5.]]])
y = np.array([[[2.], [3.], [4.], [5.], [6.]]])

print(x.shape, y.shape)

(1, 5, 1) (1, 5, 1)


In [103]:
xInput = Input(batch_shape=(None, 5, 1))
xLstm = LSTM(3, return_sequences=True)(xInput)
xOutput = TimeDistributed(Dense(1))(xLstm)

model = Model(xInput, xOutput)
model.compile(loss='mean_squared_error', optimizer='adam')
print(model.summary())

Model: "model_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_6 (InputLayer)         [(None, 5, 1)]            0         
_________________________________________________________________
lstm_5 (LSTM)                (None, 5, 3)              60        
_________________________________________________________________
time_distributed_1 (TimeDist (None, 5, 1)              4         
Total params: 64
Trainable params: 64
Non-trainable params: 0
_________________________________________________________________
None


In [112]:
model.fit(x, y, epochs=100, batch_size=1, verbose=0)
model.predict(x, batch_size=1)

array([[[1.8879142],
        [3.2692983],
        [3.869036 ],
        [4.0163   ],
        [4.056901 ]]], dtype=float32)

In [113]:
# Bidirectional LSTM

from keras.layers import Bidirectional

x = np.array([[[1.], [2.], [3.], [4.], [5.]]])
y = np.array([[6.]])

xInput = Input(batch_shape=(None, 5, 1))
xBiLstm = Bidirectional(LSTM(3), merge_mode = 'concat')(xInput)
xOutput = Dense(1)(xBiLstm)

model = Model(xInput, xOutput)
model.compile(loss='mean_squared_error', optimizer='adam')
print(model.summary())

Model: "model_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_7 (InputLayer)         [(None, 5, 1)]            0         
_________________________________________________________________
bidirectional (Bidirectional (None, 6)                 120       
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 7         
Total params: 127
Trainable params: 127
Non-trainable params: 0
_________________________________________________________________
None


In [114]:
model.fit(x, y, epochs=100, batch_size=1, verbose=0)
model.predict(x)

array([[0.4388827]], dtype=float32)

In [115]:
# Bidirectional Many to Many

x = np.array([[[1.], [2.], [3.], [4.], [5.]]])
y = np.array([[[2.], [3.], [4.], [5.], [6.]]])

xInput = Input(batch_shape=(None, 5, 1))
xBiLstm = Bidirectional(LSTM(3, return_sequences=True), \
                        merge_mode='concat')(xInput)
xOutput = TimeDistributed(Dense(1))(xBiLstm)

model = Model(xInput, xOutput)
model.compile(loss='mean_squared_error', optimizer='adam')
print(model.summary())

Model: "model_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_8 (InputLayer)         [(None, 5, 1)]            0         
_________________________________________________________________
bidirectional_1 (Bidirection (None, 5, 6)              120       
_________________________________________________________________
time_distributed_2 (TimeDist (None, 5, 1)              7         
Total params: 127
Trainable params: 127
Non-trainable params: 0
_________________________________________________________________
None


In [117]:
model.fit(x, y, epochs=200, batch_size=1, verbose=0)
model.predict(x)

array([[[2.569471 ],
        [3.2538495],
        [3.6953685],
        [3.7243948],
        [3.144647 ]]], dtype=float32)